### ISSUE TITLE
Some applications have mismatched app IDs

### ISSUE THREAD

**Issue by iBelieve** [lirios/shell#10]
- Corebird:
  - Desktop file ID: org.baedert.corebird
  - App ID: corebird
- GNOME Calendar:
  - Desktop file ID: org.gnome.Calendar
  - App ID: gnome-calendar

There are probably others, but these are the ones I've noticed so far. Not sure if this is something that can be fixed in GreenIsland or if we'll need to add mappings to find the correct desktop ID.

**Comment by plfiorini** [comment]
This is a Gtk+ bug that Green Island work around by implementing the gtk-shell protocol.
Apparently Gtk+ applications communicate the right appId with gtk-shell but not with xdg-shell, the problem is that sometimes we receive the set_app_id from gtk-shell sooner than xdg-shell sometimes after and there's a workaround in place that doesn't set the appId twice.

**Comment by plfiorini** [comment]
That's supposed to be fixed except it's not: https://bugzilla.gnome.org/show_bug.cgi?id=746435

As far as I remember g_get_prgname() returns the executable name which is not what the application id is...

**Comment by plfiorini** [comment]
I see a lot of confusion on app IDs from the GNOME camp: https://bugzilla.gnome.org/show_bug.cgi?id=752258

Reported bug here: https://bugzilla.gnome.org/show_bug.cgi?id=769641

Let's hope it will get fixed!

**Comment by iBeliever** [comment]
Temporary workaround [here](https://github.com/qmlos/libqmlos/blob/develop/src/core/desktopfile.cpp#L36).

**Comment by plfiorini** [comment]
@iBeliever We can expand on that and add a little daemon that runs periodically for each logged in user and dump a binary data structur that associates app id (that is the desktop entry base name without extension) to the executable in the Exec line. Ubuntu had something like that called bamf ages go.

Though it's sad that we keep having the same issues all over again with Wayland because toolkit developers can't get their code together after years.

**Comment by plfiorini** [comment]
That said, I'd prefer to implement the daemon as a last resort...

**Comment by plfiorini** [comment]
Bug moved to GitLab: https://gitlab.gnome.org/GNOME/gtk/issues/653

**Comment by plfiorini** [comment]
Seems like it has been fixed upstream.
