### ISSUE TITLE
Two cursors when running shell from GDM

### ISSUE THREAD

**Issue by iBeliever** [lirios/shell#19]
The black cursor lags a bit when moving the mouse and isn't always on top (popups, both in the shell and other apps, will cover it):

![img_20160817_173251](https://cloud.githubusercontent.com/assets/3230912/17756697/25fe11a4-64a7-11e6-8403-1d2dbe0da3ee.jpg)

**Comment by iBeliever** [comment]
Updated the issue to clarify what the problem actually is.

**Comment by plfiorini** [comment]
Yeah I still have the white fallback cursor on Green Island.
We need a QML component for cursors, here's the thing: with Wayland the client creates the cursor and the server just display a cursor surface and moves with mouse motion.
Since we have the shell and the compositor in once process we don't have a client that can create that cursor, hence if I disable the white fallback cursor we don't see any cursor until the an application is started; but even in that case we'd see the cursor only when it's moved on any of the app windows.

So what we need is Green Island to provide a QML component that make a Wayland client connection to itself and draw a cursor for the shell.

**Comment by plfiorini** [comment]
I'm working on this now

**Comment by zigapk** [comment]
The issue can still be reproduced, however I don't know exactly how. Seems to happen when hovering over applications menu.
![2_cursors](https://cloud.githubusercontent.com/assets/5074514/19411418/a0f9cbf4-9301-11e6-87ff-8f57302bf940.jpg)

And the remaining cursor seems to have a little bit of offset (exactly the difference between it and the system cursor seen on the first photo).
![offset_1](https://cloud.githubusercontent.com/assets/5074514/19411426/f80c5466-9301-11e6-9c98-ee22fa2828d4.jpg)
![offset_2](https://cloud.githubusercontent.com/assets/5074514/19411442/4b539724-9302-11e6-9394-f60e98e77c9e.jpg)

**Comment by plfiorini** [comment]
@zigapk Both issues should be addressed now however when you launch an application you can see the windowing system cursor for a second. I think I will change the greenisland QPA plugin to never draw the cursor so this last issue will only be visible in a X11 window which we don't care about.

**Comment by zigapk** [comment]
@plfiorini everything works fine now, except when I hover over disks list (see images).
![disk_cursor](https://cloud.githubusercontent.com/assets/5074514/19413376/8f6035d4-932b-11e6-88a3-7dea44ed5994.jpg)
![disk_cursor_2](https://cloud.githubusercontent.com/assets/5074514/19413377/938bdcd0-932b-11e6-92d6-d0c0a1278be6.jpg)

Although, never drawing the cursor will probably solve even that.

**Comment by plfiorini** [comment]
Right because there's a MouseArea there too :-/
Let's check it out again after I have removed the cursor from QPA.

**Comment by plfiorini** [comment]
Thanks for the tests.

**Comment by plfiorini** [comment]
Done!

greenisland, develop branch, doesn't draw the cursor by default.
